default: &default
  adapter: postgresql
  encoding: unicode
  timeout: 5000
  pool: <%= (ENV['RAILS_MAX_THREADS'] || 5).to_i * 2 %>
  host: <%= ENV['REL_DATABASE_HOST'] %>
  port: <%= ENV['REL_DATABASE_PORT'] %>
  username: <%= ENV['REL_DATABASE_USERNAME'] %>
  password: <%= ENV['REL_DATABASE_PASSWORD'] %>

production:
  <<: *default
  database: <%= ENV['REL_DATABASE_DATABASE'] %>

development:
  <<: *default
  database: <%= ENV['REL_DATABASE_DATABASE'] %>
