services:
  db:
    image: postgres:9.5.1
    environment:
      # ..........
  redis:
    image: redis
  proxy:
    image: nginx
  puppies_web:
    image: equivalent/eb-demo-rails:v1
    environment:
      # ..........
    links:
      - db
      - redis
      - proxy
  puppies_bg_worker:
    image: equivalent/eb-demo-rails:v1
    environment:
      # ..........
    links:
      - db
      - redis
